line-length = 100
indent-width = 4

target-version = "py313"
extend-include = ["./scripts/*.py"]

[lint]
select = [
    "YTT",
    "S",
    "BLE001",
    "FBT",
    "B",
    "A",
    "FA",
    "ISC",
    "I",
    "PT",
    "Q003",
    "RET",
    "SIM",
    "ARG",
    "NPY001",
    "E101",
    "E401",
    "E501",
    "E701",
    "E702",
    "E703",
    "E711",
    "E713",
    "E714",
    "E721",
    "E731",
    "W",
    "F",
    "PLE",
    "PLR1722",
    "PLW",
    "RUF",
    "TRY",
]
ignore = [
    # These are disabled because it feels like code is more readable without them
    "RET505", # Branch after return
    "RET506", # Branch after raise
    "RET507", # Branch after continue
    "RET508", # Branch after break
    "SIM102", # Use single if instead of nested if
    "SIM114", # if with same arms.

    # These are disabled because they aren't necessarily useful
    "PLW1641", # Implement __eq__ without __hash__

    # Greek letters are common in chemistry/condensed matter.
    "RUF001",
    "RUF002",
    "RUF003",
]

[lint.per-file-ignores]

# Line too long. Prefer long single line for enumeration members, avoids super long files
"src/avogadro_generators/orca/input_blocks/*.py" = ["E501"]
"src/avogadro_generators/orca/implicit_solvation.py" = ["E501"]
"src/avogadro_generators/orca/libxc.py" = ["E501"]
"src/avogadro_generators/orca/basis_sets.py" = ["E501"]
"src/avogadro_generators/orca/dft.py" = ["E501"]