[[default.rules]]
format.preset = "comment"
patterns = [
    { regexp = '#[^\n]*' },
]

[[default.rules]]
format.preset = "num_literal"
patterns = [
    { regexp = '\b[+-]?[.0-9]+(?:[eEdD][+-]?[.0-9]+)?\b' },
]

[[default.rules]]
format.preset = "str_literal"
patterns = [
    { regexp = '\b(?i)True\b' },
    { regexp = '\b(?i)False\b' },
    { regexp = '\b(?i)H\b' },
    { regexp = '\b(?i)He\b' },
    { regexp = '\b(?i)Li\b' },
    { regexp = '\b(?i)Be\b' },
    { regexp = '\b(?i)B\b' },
    { regexp = '\b(?i)C\b' },
    { regexp = '\b(?i)N\b' },
    { regexp = '\b(?i)O\b' },
    { regexp = '\b(?i)F\b' },
    { regexp = '\b(?i)Ne\b' },
    { regexp = '\b(?i)Na\b' },
    { regexp = '\b(?i)Mg\b' },
    { regexp = '\b(?i)Al\b' },
    { regexp = '\b(?i)Si\b' },
    { regexp = '\b(?i)P\b' },
    { regexp = '\b(?i)S\b' },
    { regexp = '\b(?i)Cl\b' },
    { regexp = '\b(?i)Ar\b' },
    { regexp = '\b(?i)K\b' },
    { regexp = '\b(?i)Ca\b' },
    { regexp = '\b(?i)Sc\b' },
    { regexp = '\b(?i)Ti\b' },
    { regexp = '\b(?i)V\b' },
    { regexp = '\b(?i)Cr\b' },
    { regexp = '\b(?i)Mn\b' },
    { regexp = '\b(?i)Fe\b' },
    { regexp = '\b(?i)Co\b' },
    { regexp = '\b(?i)Ni\b' },
    { regexp = '\b(?i)Cu\b' },
    { regexp = '\b(?i)Zn\b' },
    { regexp = '\b(?i)Ga\b' },
    { regexp = '\b(?i)Ge\b' },
    { regexp = '\b(?i)As\b' },
    { regexp = '\b(?i)Se\b' },
    { regexp = '\b(?i)Br\b' },
    { regexp = '\b(?i)Kr\b' },
    { regexp = '\b(?i)Rb\b' },
    { regexp = '\b(?i)Sr\b' },
    { regexp = '\b(?i)Y\b' },
    { regexp = '\b(?i)Zr\b' },
    { regexp = '\b(?i)Nb\b' },
    { regexp = '\b(?i)Mo\b' },
    { regexp = '\b(?i)Tc\b' },
    { regexp = '\b(?i)Ru\b' },
    { regexp = '\b(?i)Rh\b' },
    { regexp = '\b(?i)Pd\b' },
    { regexp = '\b(?i)Ag\b' },
    { regexp = '\b(?i)Cd\b' },
    { regexp = '\b(?i)In\b' },
    { regexp = '\b(?i)Sn\b' },
    { regexp = '\b(?i)Sb\b' },
    { regexp = '\b(?i)Te\b' },
    { regexp = '\b(?i)I\b' },
    { regexp = '\b(?i)Xe\b' },
    { regexp = '\b(?i)Cs\b' },
    { regexp = '\b(?i)Ba\b' },
    { regexp = '\b(?i)La\b' },
    { regexp = '\b(?i)Ce\b' },
    { regexp = '\b(?i)Pr\b' },
    { regexp = '\b(?i)Nd\b' },
    { regexp = '\b(?i)Pm\b' },
    { regexp = '\b(?i)Sm\b' },
    { regexp = '\b(?i)Eu\b' },
    { regexp = '\b(?i)Gd\b' },
    { regexp = '\b(?i)Tb\b' },
    { regexp = '\b(?i)Dy\b' },
    { regexp = '\b(?i)Ho\b' },
    { regexp = '\b(?i)Er\b' },
    { regexp = '\b(?i)Tm\b' },
    { regexp = '\b(?i)Yb\b' },
    { regexp = '\b(?i)Lu\b' },
    { regexp = '\b(?i)Hf\b' },
    { regexp = '\b(?i)Ta\b' },
    { regexp = '\b(?i)W\b' },
    { regexp = '\b(?i)Re\b' },
    { regexp = '\b(?i)Os\b' },
    { regexp = '\b(?i)Ir\b' },
    { regexp = '\b(?i)Pt\b' },
    { regexp = '\b(?i)Au\b' },
    { regexp = '\b(?i)Hg\b' },
    { regexp = '\b(?i)Tl\b' },
    { regexp = '\b(?i)Pb\b' },
    { regexp = '\b(?i)Bi\b' },
    { regexp = '\b(?i)Po\b' },
    { regexp = '\b(?i)At\b' },
    { regexp = '\b(?i)Rn\b' },
    { regexp = '\b(?i)Fr\b' },
    { regexp = '\b(?i)Ra\b' },
    { regexp = '\b(?i)Ac\b' },
    { regexp = '\b(?i)Th\b' },
    { regexp = '\b(?i)Pa\b' },
    { regexp = '\b(?i)U\b' },
    { regexp = '\b(?i)Np\b' },
    { regexp = '\b(?i)Pu\b' },
    { regexp = '\b(?i)Am\b' },
    { regexp = '\b(?i)Cm\b' },
    { regexp = '\b(?i)Bk\b' },
    { regexp = '\b(?i)Cf\b' },
    { regexp = '\b(?i)Es\b' },
    { regexp = '\b(?i)Fm\b' },
    { regexp = '\b(?i)Md\b' },
    { regexp = '\b(?i)No\b' },
    { regexp = '\b(?i)Lr\b' },
    { regexp = '\b(?i)Rf\b' },
    { regexp = '\b(?i)Db\b' },
    { regexp = '\b(?i)Sg\b' },
    { regexp = '\b(?i)Bh\b' },
    { regexp = '\b(?i)Hs\b' },
    { regexp = '\b(?i)Mt\b' },
    { regexp = '\b(?i)Ds\b' },
    { regexp = '\b(?i)Rg\b' },
    { regexp = '\b(?i)Cn\b' },
    { regexp = '\b(?i)Nh\b' },
    { regexp = '\b(?i)Fl\b' },
    { regexp = '\b(?i)Mc\b' },
    { regexp = '\b(?i)Lv\b' },
    { regexp = '\b(?i)Ts\b' },
    { regexp = '\b(?i)Og\b' },
]

[[default.rules]]
format.preset = "method"
patterns = [
    { regexp = '\b(?i)HF-3c\b' },
    { regexp = '\b(?i)B97-3c\b' },
    { regexp = '\b(?i)r2SCAN-3c\b' },
    { regexp = '\b(?i)PBEh-3c\b' },
    { regexp = '\b(?i)B3LYP-3c\b' },
    { regexp = '\b(?i)wB97X-3c\b' },
    { regexp = '\b(?i)HFS\b' },
    { regexp = '\b(?i)LDA\b' },
    { regexp = '\b(?i)VWN5\b' },
    { regexp = '\b(?i)VWN3\b' },
    { regexp = '\b(?i)PWLDA\b' },
    { regexp = '\b(?i)BP86\b' },
    { regexp = '\b(?i)BLYP\b' },
    { regexp = '\b(?i)OLYP\b' },
    { regexp = '\b(?i)GLYP\b' },
    { regexp = '\b(?i)XLYP\b' },
    { regexp = '\b(?i)PW91\b' },
    { regexp = '\b(?i)mPWPW\b' },
    { regexp = '\b(?i)mPWLYP\b' },
    { regexp = '\b(?i)PBE\b' },
    { regexp = '\b(?i)RPBE\b' },
    { regexp = '\b(?i)revPBE\b' },
    { regexp = '\b(?i)RPW86PBE\b' },
    { regexp = '\b(?i)PWP\b' },
    { regexp = '\b(?i)B97M-V\b' },
    { regexp = '\b(?i)B97M-D3BJ\b' },
    { regexp = '\b(?i)B97M-D4\b' },
    { regexp = '\b(?i)SCANFUNC\b' },
    { regexp = '\b(?i)rSCAN\b' },
    { regexp = '\b(?i)r2SCAN\b' },
    { regexp = '\b(?i)M06L\b' },
    { regexp = '\b(?i)TPSS\b' },
    { regexp = '\b(?i)revTPSS\b' },
    { regexp = '\b(?i)B1LYP\b' },
    { regexp = '\b(?i)B3LYP\b' },
    { regexp = '\b(?i)B3LYP/G\b' },
    { regexp = '\b(?i)O3LYP\b' },
    { regexp = '\b(?i)X3LYP\b' },
    { regexp = '\b(?i)B1P86\b' },
    { regexp = '\b(?i)B3P86\b' },
    { regexp = '\b(?i)B3PW91\b' },
    { regexp = '\b(?i)PW1PW\b' },
    { regexp = '\b(?i)mPW1PW\b' },
    { regexp = '\b(?i)mPW1LYP\b' },
    { regexp = '\b(?i)PBE0\b' },
    { regexp = '\b(?i)revPBE0\b' },
    { regexp = '\b(?i)revPBE38\b' },
    { regexp = '\b(?i)BHandHLYP\b' },
    { regexp = '\b(?i)M06\b' },
    { regexp = '\b(?i)M062X\b' },
    { regexp = '\b(?i)PW6B95\b' },
    { regexp = '\b(?i)TPSSh\b' },
    { regexp = '\b(?i)TPSS0\b' },
    { regexp = '\b(?i)r2SCANh\b' },
    { regexp = '\b(?i)r2SCAN0\b' },
    { regexp = '\b(?i)r2SCAN50\b' },
    { regexp = '\b(?i)wB97\b' },
    { regexp = '\b(?i)wB97X\b' },
    { regexp = '\b(?i)wB97X-V\b' },
    { regexp = '\b(?i)wB97X-D3\b' },
    { regexp = '\b(?i)wB97X-D3BJ\b' },
    { regexp = '\b(?i)wB97X-D4\b' },
    { regexp = '\b(?i)wB97X-D4rev\b' },
    { regexp = '\b(?i)CAM-B3LYP\b' },
    { regexp = '\b(?i)LC-BLYP\b' },
    { regexp = '\b(?i)LC-PBE\b' },
    { regexp = '\b(?i)wB97M-V\b' },
    { regexp = '\b(?i)wB97M-D3BJ\b' },
    { regexp = '\b(?i)wB97M-D4\b' },
    { regexp = '\b(?i)wB97M-D4rev\b' },
    { regexp = '\b(?i)wr2SCAN\b' },
    { regexp = '\b(?i)DSD-BLYP D3BJ\b' },
    { regexp = '\b(?i)DSD-BLYP/2013\b' },
    { regexp = '\b(?i)DSD-BLYP/2013 D3BJ\b' },
    { regexp = '\b(?i)DSD-PBEP86 D3BJ\b' },
    { regexp = '\b(?i)DSD-PBEP86/2013\b' },
    { regexp = '\b(?i)DSD-PBEP86/2013 D3BJ\b' },
    { regexp = '\b(?i)DSD-PBEB95\b' },
    { regexp = '\b(?i)DSD-PBEB95 D3BJ\b' },
    { regexp = '\b(?i)B2PLYP\b' },
    { regexp = '\b(?i)mPW2PLYP\b' },
    { regexp = '\b(?i)B2GP-PLYP\b' },
    { regexp = '\b(?i)B2K-PLYP\b' },
    { regexp = '\b(?i)B2T-PLYP\b' },
    { regexp = '\b(?i)B2NC-PLYP\b' },
    { regexp = '\b(?i)PWPB95\b' },
    { regexp = '\b(?i)PBE-QIDH\b' },
    { regexp = '\b(?i)PBE0-DH\b' },
    { regexp = '\b(?i)revDSD-PBEP86/2021\b' },
    { regexp = '\b(?i)revDSD-PBEP86-D4/2021\b' },
    { regexp = '\b(?i)revDOD-PBEP86/2021\b' },
    { regexp = '\b(?i)revDOD-PBEP86-D4/2021\b' },
    { regexp = '\b(?i)r2SCAN-CIDH\b' },
    { regexp = '\b(?i)r2SCAN-QIDH\b' },
    { regexp = '\b(?i)r2SCAN0-2\b' },
    { regexp = '\b(?i)r2SCAN0-DH\b' },
    { regexp = '\b(?i)Pr2SCAN50\b' },
    { regexp = '\b(?i)Pr2SCAN69\b' },
    { regexp = '\b(?i)kPr2SCAN\b' },
    { regexp = '\b(?i)SCS/SOS-B2PLYP21\b' },
    { regexp = '\b(?i)SCS-PBE-QIDH\b' },
    { regexp = '\b(?i)SOS-PBE-QIDH\b' },
    { regexp = '\b(?i)SCS-B2GP-PLYP21\b' },
    { regexp = '\b(?i)SOS-B2GP-PLYP21\b' },
    { regexp = '\b(?i)MP2\b' },
    { regexp = '\b(?i)RI-MP2\b' },
    { regexp = '\b(?i)DLPNO-MP2\b' },
    { regexp = '\b(?i)SCS-MP2\b' },
    { regexp = '\b(?i)SCS-MP2\b' },
    { regexp = '\b(?i)SCS-RI-MP2\b' },
    { regexp = '\b(?i)SOS-RI-MP2\b' },
    { regexp = '\b(?i)SCS-DLPNO-MP2\b' },
    { regexp = '\b(?i)SOS-DLPNO-MP2\b' },
    { regexp = '\b(?i)OO-RI-MP2\b' },
    { regexp = '\b(?i)OO-SCS-RI-MP2\b' },
    { regexp = '\b(?i)OO-SOS-RI-MP2\b' },
    { regexp = '\b(?i)F12-MP2\b' },
    { regexp = '\b(?i)F12-RI-MP2\b' },
    { regexp = '\b(?i)F12/D-RI-MP2\b' },
    { regexp = '\b(?i)F12-DLPNO-MP2\b' },
    { regexp = '\b(?i)F12/D-DLPNO-MP2\b' },
    { regexp = '\b(?i)CCSD\b' },
    { regexp = '\b(?i)RI-CCSD\b' },
    { regexp = '\b(?i)CCSD\(T\)\b' },
    { regexp = '\b(?i)RI-CCSD\(T\)\b' },
    { regexp = '\b(?i)CCSD-F12\b' },
    { regexp = '\b(?i)CCSD\(T\)-F12\b' },
    { regexp = '\b(?i)CCSD-F12/RI\b' },
    { regexp = '\b(?i)CCSD-F12D/RI\b' },
    { regexp = '\b(?i)CCSD\(T\)-F12/RI\b' },
    { regexp = '\b(?i)CCSD\(T\)-F12D/RI\b' },
    { regexp = '\b(?i)DLPNO-CCSD\b' },
    { regexp = '\b(?i)DLPNO-CCSD\(T\)\b' },
    { regexp = '\b(?i)DLPNO-CCSD\(T1\)\b' },
    { regexp = '\b(?i)DLPNO-CCSD-F12\b' },
    { regexp = '\b(?i)DLPNO-CCSD-F12/D\b' },
    { regexp = '\b(?i)DLPNO-CCSD\(T\)-F12\b' },
    { regexp = '\b(?i)DLPNO-CCSD\(T\)-F12/D\b' },
    { regexp = '\b(?i)DLPNO-CCSD\(T1\)-F12\b' },
    { regexp = '\b(?i)DLPNO-CCSD\(T1\)-F12/D\b' },
]