[[default.rules]]
format.preset = "keyword"
patterns = [
    # xTB methods
    { regexp = '\b(?:Native-)?GFN[012]-xTB\s', caseSensitive = false },
    # NDO Methods (ZNNDO, ZINDO, etc.)
    { regexp = '\bZ[IN][ND]DO\/[12S]\s', caseSensitive = false },
    # SCF and Opt convergence criteria
    { regexp = '\b(?:Sloppy|Loose|Medium|Strong|Tight|VeryTight|Extreme){1}(?:SCF|Opt){1}\s', caseSensitive = false },
    # RHF, UHF, ROHF, RKS, UKS, ROKS
    { regexp = '\b(?:R|U|RO){1}(?:HF|KS){1}\s', caseSensitive = false },
    # Print levels
    { regexp = '\b(?:Mini|Small|Normal|Large){1}Print\s', caseSensitive = false },
    # DEFGRIDn
    { regexp = '\bDEFGRID[123]{1}\s', caseSensitive = false },
    # DKHn
    { regexp = '\bDKH[12]{1}\s', caseSensitive = false },
    # PNO settings
    { regexp = '\b(?:Loose|Normal|Tight){1}PNO\s', caseSensitive = false },
    # CPCM/SMD/COSMO
    { regexp = '\b(?:CPCMC?|SMD|COSMORS){1}\([\w,-]*\)\s', caseSensitive = false },
    # Everything else
    { string = "SP"},
    { string = "EnGrad"},
    { string = "Opt"},
    { string = "OptTS"},
    { string = "Freq"},
    { string = "NumFreq"},
    { string = "MD"},
    { string = "AM1"},
    { string = "PM3"},
    { string = "MNDO"},
    { string = "PrintGap"},
    { string = "PrintMOs"},
    { string = "PrintBasis"},
    { string = "AIM"},
    { string = "XYZFile"},
    { string = "PDBFile"},
    { string = "UNO"},
    { string = "NoPropFile"},
    { string = "KeepTransDensity"},
    { string = "COSJXC"},
    { string = "NoCOSX"},
    { regexp = '\bRI\h', caseSensitive = false},
    { string = "NoRI"},
    { string = "RIJCOSX"},
    { string = "NoRIJCOSX"},
    { string = "Split-RI-J"},
    { string = "NoSplit-RI-J"},
    { string = "RI-JK"},
    { string = "AIM"},
    { string = "CHELPG"},
    { string = "Hirshfeld"},
    { string = "Loewdin"},
    { string = "Mayer"},
    { string = "MBIS"},
    { string = "Mulliken"},
    { string = "ZORA"},
    { string = "IORA"},
    { string = "X2C"},
]

[[default.rules]]
format.preset = "comment"
patterns = [
    # ORCA comments can either be any line with a # at the start
    # or it can be any text enclosed by two #'s
    { regexp = '(?:#[^\n]*#|#[^\n]*)' },
]

[[default.rules]]
format.preset = "num_literal"
patterns = [
    { regexp = '\s[-\+]?[\.0-9]+(?:[eEdD][-\+]?[\.0-9]+)?\b' },
]

[[default.rules]]
format.preset = "str_literal"
patterns = [
    { regexp = '\bTrue\b', caseSensitive = false },
    { regexp = '\bFalse\b', caseSensitive = false },
    { regexp = '\bH\b'  },
    { regexp = '\bHe\b' },
    { regexp = '\bLi\b' },
    { regexp = '\bBe\b' },
    { regexp = '\bB\b'  },
    { regexp = '\bC\b'  },
    { regexp = '\bN\b'  },
    { regexp = '\bO\b'  },
    { regexp = '\bF\b'  },
    { regexp = '\bNe\b' },
    { regexp = '\bNa\b' },
    { regexp = '\bMg\b' },
    { regexp = '\bAl\b' },
    { regexp = '\bSi\b' },
    { regexp = '\bP\b'  },
    { regexp = '\bS\b'  },
    { regexp = '\bCl\b' },
    { regexp = '\bAr\b' },
    { regexp = '\bK\b'  },
    { regexp = '\bCa\b' },
    { regexp = '\bSc\b' },
    { regexp = '\bTi\b' },
    { regexp = '\bV\b'  },
    { regexp = '\bCr\b' },
    { regexp = '\bMn\b' },
    { regexp = '\bFe\b' },
    { regexp = '\bCo\b' },
    { regexp = '\bNi\b' },
    { regexp = '\bCu\b' },
    { regexp = '\bZn\b' },
    { regexp = '\bGa\b' },
    { regexp = '\bGe\b' },
    { regexp = '\bAs\b' },
    { regexp = '\bSe\b' },
    { regexp = '\bBr\b' },
    { regexp = '\bKr\b' },
    { regexp = '\bRb\b' },
    { regexp = '\bSr\b' },
    { regexp = '\bY\b'  },
    { regexp = '\bZr\b' },
    { regexp = '\bNb\b' },
    { regexp = '\bMo\b' },
    { regexp = '\bTc\b' },
    { regexp = '\bRu\b' },
    { regexp = '\bRh\b' },
    { regexp = '\bPd\b' },
    { regexp = '\bAg\b' },
    { regexp = '\bCd\b' },
    { regexp = '\bIn\b' },
    { regexp = '\bSn\b' },
    { regexp = '\bSb\b' },
    { regexp = '\bTe\b' },
    { regexp = '\bI\b'  },
    { regexp = '\bXe\b' },
    { regexp = '\bCs\b' },
    { regexp = '\bBa\b' },
    { regexp = '\bLa\b' },
    { regexp = '\bCe\b' },
    { regexp = '\bPr\b' },
    { regexp = '\bNd\b' },
    { regexp = '\bPm\b' },
    { regexp = '\bSm\b' },
    { regexp = '\bEu\b' },
    { regexp = '\bGd\b' },
    { regexp = '\bTb\b' },
    { regexp = '\bDy\b' },
    { regexp = '\bHo\b' },
    { regexp = '\bEr\b' },
    { regexp = '\bTm\b' },
    { regexp = '\bYb\b' },
    { regexp = '\bLu\b' },
    { regexp = '\bHf\b' },
    { regexp = '\bTa\b' },
    { regexp = '\bW\b'  },
    { regexp = '\bRe\b' },
    { regexp = '\bOs\b' },
    { regexp = '\bIr\b' },
    { regexp = '\bPt\b' },
    { regexp = '\bAu\b' },
    { regexp = '\bHg\b' },
    { regexp = '\bTl\b' },
    { regexp = '\bPb\b' },
    { regexp = '\bBi\b' },
    { regexp = '\bPo\b' },
    { regexp = '\bAt\b' },
    { regexp = '\bRn\b' },
    { regexp = '\bFr\b' },
    { regexp = '\bRa\b' },
    { regexp = '\bAc\b' },
    { regexp = '\bTh\b' },
    { regexp = '\bPa\b' },
    { regexp = '\bU\b'  },
    { regexp = '\bNp\b' },
    { regexp = '\bPu\b' },
    { regexp = '\bAm\b' },
    { regexp = '\bCm\b' },
    { regexp = '\bBk\b' },
    { regexp = '\bCf\b' },
    { regexp = '\bEs\b' },
    { regexp = '\bFm\b' },
    { regexp = '\bMd\b' },
    { regexp = '\bNo\b' },
    { regexp = '\bLr\b' },
    { regexp = '\bRf\b' },
    { regexp = '\bDb\b' },
    { regexp = '\bSg\b' },
    { regexp = '\bBh\b' },
    { regexp = '\bHs\b' },
    { regexp = '\bMt\b' },
    { regexp = '\bDs\b' },
    { regexp = '\bRg\b' },
    { regexp = '\bCn\b' },
    { regexp = '\bNh\b' },
    { regexp = '\bFl\b' },
    { regexp = '\bMc\b' },
    { regexp = '\bLv\b' },
    { regexp = '\bTs\b' },
    { regexp = '\bOg\b' },
]

[[default.rules]]
format.preset = "method"
patterns = [
    # Built in Functionals
    { string = "HF-3c",                 caseSensitive = false },
    { string = "B97-3c",                caseSensitive = false },
    { string = "r2SCAN-3c",             caseSensitive = false },
    { string = "PBEh-3c",               caseSensitive = false },
    { string = "B3LYP-3c",              caseSensitive = false },
    { string = "wB97X-3c",              caseSensitive = false },
    { string = "HFS",                   caseSensitive = false },
    { string = "LDA",                   caseSensitive = false },
    { string = "VWN5",                  caseSensitive = false },
    { string = "VWN3",                  caseSensitive = false },
    { string = "PWLDA",                 caseSensitive = false },
    { string = "BP86",                  caseSensitive = false },
    { string = "BLYP",                  caseSensitive = false },
    { string = "OLYP",                  caseSensitive = false },
    { string = "GLYP",                  caseSensitive = false },
    { string = "XLYP",                  caseSensitive = false },
    { string = "PW91",                  caseSensitive = false },
    { string = "mPWPW",                 caseSensitive = false },
    { string = "mPWLYP",                caseSensitive = false },
    { string = "PBE",                   caseSensitive = false },
    { string = "RPBE",                  caseSensitive = false },
    { string = "revPBE",                caseSensitive = false },
    { string = "RPW86PBE",              caseSensitive = false },
    { string = "PWP",                   caseSensitive = false },
    { string = "B97M-V",                caseSensitive = false },
    { string = "B97M-D3BJ",             caseSensitive = false },
    { string = "B97M-D4",               caseSensitive = false },
    { string = "SCANFUNC",              caseSensitive = false },
    { string = "rSCAN",                 caseSensitive = false },
    { string = "r2SCAN",                caseSensitive = false },
    { string = "M06L",                  caseSensitive = false },
    { string = "TPSS",                  caseSensitive = false },
    { string = "revTPSS",               caseSensitive = false },
    { string = "B1LYP",                 caseSensitive = false },
    { string = "B3LYP",                 caseSensitive = false },
    { string = "B3LYP/G",               caseSensitive = false },
    { string = "O3LYP",                 caseSensitive = false },
    { string = "X3LYP",                 caseSensitive = false },
    { string = "B1P86",                 caseSensitive = false },
    { string = "B3P86",                 caseSensitive = false },
    { string = "B3PW91",                caseSensitive = false },
    { string = "PW1PW",                 caseSensitive = false },
    { string = "mPW1PW",                caseSensitive = false },
    { string = "mPW1LYP",               caseSensitive = false },
    { string = "PBE0",                  caseSensitive = false },
    { string = "revPBE0",               caseSensitive = false },
    { string = "revPBE38",              caseSensitive = false },
    { string = "BHandHLYP",             caseSensitive = false },
    { string = "M06",                   caseSensitive = false },
    { string = "M062X",                 caseSensitive = false },
    { string = "PW6B95",                caseSensitive = false },
    { string = "TPSSh",                 caseSensitive = false },
    { string = "TPSS0",                 caseSensitive = false },
    { string = "r2SCANh",               caseSensitive = false },
    { string = "r2SCAN0",               caseSensitive = false },
    { string = "r2SCAN50",              caseSensitive = false },
    { string = "wB97",                  caseSensitive = false },
    { string = "wB97X",                 caseSensitive = false },
    { string = "wB97X-V",               caseSensitive = false },
    { string = "wB97X-D3",              caseSensitive = false },
    { string = "wB97X-D3BJ",            caseSensitive = false },
    { string = "wB97X-D4",              caseSensitive = false },
    { string = "wB97X-D4rev",           caseSensitive = false },
    { string = "CAM-B3LYP",             caseSensitive = false },
    { string = "LC-BLYP",               caseSensitive = false },
    { string = "LC-PBE",                caseSensitive = false },
    { string = "wB97M-V",               caseSensitive = false },
    { string = "wB97M-D3BJ",            caseSensitive = false },
    { string = "wB97M-D4",              caseSensitive = false },
    { string = "wB97M-D4rev",           caseSensitive = false },
    { string = "wr2SCAN",               caseSensitive = false },
    { string = "DSD-BLYP D3BJ",         caseSensitive = false },
    { string = "DSD-BLYP/2013",         caseSensitive = false },
    { string = "DSD-BLYP/2013 D3BJ",    caseSensitive = false },
    { string = "DSD-PBEP86 D3BJ",       caseSensitive = false },
    { string = "DSD-PBEP86/2013",       caseSensitive = false },
    { string = "DSD-PBEP86/2013 D3BJ",  caseSensitive = false },
    { string = "DSD-PBEB95",            caseSensitive = false },
    { string = "DSD-PBEB95 D3BJ",       caseSensitive = false },
    { string = "B2PLYP",                caseSensitive = false },
    { string = "mPW2PLYP",              caseSensitive = false },
    { string = "B2GP-PLYP",             caseSensitive = false },
    { string = "B2K-PLYP",              caseSensitive = false },
    { string = "B2T-PLYP",              caseSensitive = false },
    { string = "B2NC-PLYP",             caseSensitive = false },
    { string = "PWPB95",                caseSensitive = false },
    { string = "PBE-QIDH",              caseSensitive = false },
    { string = "PBE0-DH",               caseSensitive = false },
    { string = "revDSD-PBEP86/2021",    caseSensitive = false },
    { string = "revDSD-PBEP86-D4/2021", caseSensitive = false },
    { string = "revDOD-PBEP86/2021",    caseSensitive = false },
    { string = "revDOD-PBEP86-D4/2021", caseSensitive = false },
    { string = "r2SCAN-CIDH",           caseSensitive = false },
    { string = "r2SCAN-QIDH",           caseSensitive = false },
    { string = "r2SCAN0-2",             caseSensitive = false },
    { string = "r2SCAN0-DH",            caseSensitive = false },
    { string = "Pr2SCAN50",             caseSensitive = false },
    { string = "Pr2SCAN69",             caseSensitive = false },
    { string = "kPr2SCAN",              caseSensitive = false },
    { string = "SCS/SOS-B2PLYP21",      caseSensitive = false },
    { string = "SCS-PBE-QIDH",          caseSensitive = false },
    { string = "SOS-PBE-QIDH",          caseSensitive = false },
    { string = "SCS-B2GP-PLYP21",       caseSensitive = false },
    { string = "SOS-B2GP-PLYP21",       caseSensitive = false },
    # LibXC Only
    { string = "B97-D",            caseSensitive = false },
    { string = "B97-D3",           caseSensitive = false },
    { string = "B97-D4",           caseSensitive = false },
    { string = "BPBE",             caseSensitive = false },
    { string = "BPW91",            caseSensitive = false },
    { string = "BVWN",             caseSensitive = false },
    { string = "KT2",              caseSensitive = false },
    { string = "KT3",              caseSensitive = false },
    { string = "PW86PBE",          caseSensitive = false },
    { string = "MN15L",            caseSensitive = false },
    { string = "MTASK-LDA",        caseSensitive = false },
    { string = "MTASK-SCAN",       caseSensitive = false },
    { string = "REVTM",            caseSensitive = false },
    { string = "LibXC(SCAN)",      caseSensitive = false }, # Added LibXC(...) to avoid confusion with SCAN keyword
    { string = "TASK-CCALDA",      caseSensitive = false },
    { string = "TASK-CC",          caseSensitive = false },
    { string = "TASK-LDA",         caseSensitive = false },
    { string = "TASK-SCAN",        caseSensitive = false },
    { string = "TM",               caseSensitive = false },
    { string = "HFLDA",            caseSensitive = false },
    { string = "B1PW",             caseSensitive = false },
    { string = "B1PBE",            caseSensitive = false },
    { string = "B3LYPS",           caseSensitive = false },
    { string = "BLYP35",           caseSensitive = false },
    { string = "B97",              caseSensitive = false },
    { string = "CASE21",           caseSensitive = false },
    { string = "G1LYP",            caseSensitive = false },
    { string = "HSE03",            caseSensitive = false },
    { string = "HSE12",            caseSensitive = false },
    { string = "HSE12S",           caseSensitive = false },
    { string = "HSESOL",           caseSensitive = false },
    { string = "KMLYP",            caseSensitive = false },
    { string = "LB07",             caseSensitive = false },
    { string = "PBE38",            caseSensitive = false },
    { string = "PBE50",            caseSensitive = false },
    { string = "PW91_0",           caseSensitive = false },
    { string = "WHPBE0",           caseSensitive = false },
    { string = "GAS22",            caseSensitive = false },
    { string = "M05",              caseSensitive = false },
    { string = "M052X",            caseSensitive = false },
    { string = "M06SX",            caseSensitive = false },
    { string = "MN15",             caseSensitive = false },
    { string = "LC-TMLYP",         caseSensitive = false },
    { string = "R2SCAN38",         caseSensitive = false },
    { string = "SCAN0",            caseSensitive = false },
    { string = "DSD-PBEB95-D3",    caseSensitive = false },
    { string = "DSD-PBEB95-D4",    caseSensitive = false },
    { string = "MPW2-PLYP",        caseSensitive = false },
    { string = "PBE0-2",           caseSensitive = false },
    { string = "SOS1-R2SCAN0-DH",  caseSensitive = false },
    { string = "SOS1-R2SCAN-CIDH", caseSensitive = false },
    { string = "SOS1-R2SCAN-QIDH", caseSensitive = false },
    { string = "SOS1-R2SCAN0-2",   caseSensitive = false },
    # MP2
    { regexp = '\b(?:RI-()|S[CO]S-()|OO-()|F12(?:-D|D|\/D)?-()|DLPNO-){0,3}MP2\s', caseSensitive = false },
    # Coupled-Cluster methods
    { regexp = '\b(?:RI|DLPNO)?-?CCSD(?:\(T1?\))?(?:-F12(?:D|\/D)?(?:\/RI)?)?\s', caseSensitive = false },
    # LibXC Functionals - This is deliberately left vague.
    { regexp = '\b(?:hyb_)?(?:lda|m?gga)_(?:xc|[xc]{1})_?[a-z0-9_]*\s' },
]

[[default.rules]]
format.preset = "basis"
patterns = [
    # STO-nG
    { regexp = '\bSTO-[0-9]*G\s' },
    # Pople basis sets
    { regexp = '\bm?[346]-[23][12]*\+*G(?:\([23]?[dfp]{1,2},?[23]?[dfp]{0,2}\)|\**)?[SP]{0,2}\s', caseSensitive = false },
    # def2 basis sets, some of the AuxJ variants, and all of the AuxC variants
    { regexp = '\b(?:ma-)?def2-m?[STQ]?[ZVPD()]{1,5}(?:\(-f\))?(?:\/J|\/C)?\s', caseSensitive = false },
    # def2/J, def2/JK, def2/JKsmall, x2c/J, SARC/J
    { regexp = '\b(?:def2|x2c|SARC)(?:\/J|\/JK)(?:small)?\s', caseSensitive = false },
    # Jensen polarization consistent (pc) basis sets
    { regexp = '\b(?:aug-)?pc[XJH]?S?(?:seg)?-[0-9]?\s', caseSensitive = false },
    # Correlation Consistent cc-pVnZ basis sets
    { regexp = '\b(?:m?aug)?(?:apr)?(?:may)?(?:ju[nl]?)?-?cc-p[wC]{0,2}V[DTQ56]?(?:[DTQ56]|\([DTQ56]?\+d\))Z(?:-DK3?)?(?:\/JK|\/C)?\s', caseSensitive = false },
    # DKH, ZORA, SARC/SARC2 basis sets
    { regexp = '\b(?:ma-)?(?:SARC-|SARC2-)?(?:DKH-|ZORA-){1}(?:def2-)?m?[STQ]?[ZVPD()]{1,5}\(?-?f?\)?(?:\/JK)?\s', caseSensitive = false },
    # x2c basis sets
    { regexp = '\bx2c-[STQ][VZ]{1,2}[P()]{1,3}all(?:-2c)?(?:-s)?\s', caseSensitive = false },
    # ANO-RCC Basis Sets
    { regexp = '\bANO-RCC-(?:Full|[DTQ]ZP)\s', caseSensitive = false },
]

[[default.rules]]
format.preset = "block"
patterns = [
    { regexp = '%[a-zA-Z2]+\s?' },
    { regexp = '\bend\s?', caseSensitive = false },
    { regexp = '\* xyz', caseSensitive = false },
    { regexp = '\*' },
    { regexp = '!' },
]