name: lint_python

on: [pull_request, push]

jobs:
  lint_python:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/setup-uv@v10.0.1
        with:
          version: "0.12.5"
          python-version: 3.14
      - run: uv pip install ruff codespell pytest pytest-random-order safety
      - run: ruff format --config="ruff.toml" --check src scripts
      - run: codespell --ignore-words-list="ba,nd,te,adrea"
      - run: safety check
      - run: ruff check --config="ruff.toml" src scripts
